In [2]:
import torch

In [3]:
import torch.nn as nn

In [12]:
torch.manual_seed(42)
input = torch.tensor([1.0, 2.0, 3.0])

In [13]:
neuron = nn.Linear(in_features=3, out_features=1)

In [14]:
output = neuron(input)

In [15]:
output

tensor([1.5244], grad_fn=<ViewBackward0>)

In [16]:
neuron.weight

Parameter containing:
tensor([[ 0.4414,  0.4792, -0.1353]], requires_grad=True)

In [17]:
neuron.bias

Parameter containing:
tensor([0.5304], requires_grad=True)

In [18]:
neuron.weight @ input + neuron.bias

tensor([1.5244], grad_fn=<AddBackward0>)